###############################################################################################
##################
####### Project: Bernadouze | Remote sensing on vegetation
####### Title: JSDM model to predict species occurrences across site
####### Date: 07/07/2026
############################################################################################
#packages from github
#devtools::install_github("ghislainv/jSDM")

rm(list=ls(all=TRUE))

###set working directory ----

setwd("WORKING_DIRECTORY_LOCATION/Data")

###packages ----

library(dplyr)
library(tidyverse)
library(future.apply)
library(doParallel)
library(foreach)
library(jSDM)
library(HDInterval)

###data import ----

veg <- read.csv("Plot data/UAV_VEGETATION.csv") #vegetation presence-absence matrix
env <- read.csv("Plot data/UAV_VIs.csv") #VIs predictors

#data correction to correct PAR effect on Sentinel-2 images (optional)

#envs2 <- env %>% dplyr::select(TEMP, PAR)
#mod <- rda(env~., envs2)
#anova(mod, by='terms', perm=99)
#datas2.det = as.data.frame(resid(lm(as.matrix(env~., data=envs2)))

#data preparation (sorting species and removing rarest species) (optional)

#sorting <- as.data.frame(colSums(veg))
#colnames(sorting) <- c("colsum")
#sorting <- subset(sorting, colsum>1) #keep species present at least once
#sorting$species <- row.names(sorting)
#veg_sorted <- veg[,sorting$species] #remove rare compounds (20% threshold)
#veg_sorted_pa <- decostand(veg_sorted, "pa")

###starting parameters ----

#load libraries for clustering MCMC chains calculation
require(doParallel)
require(foreach)

#make a cluster for parallel MCMC chains
nchains <- 4
ncores <- nchains/2 #One core for each MCMC chains
clust <- makeCluster(ncores)
registerDoParallel(clust)

#same starting values for the four chains
nsite <- 27 #number of samples
nsp <- 33 #number of species in species matrix after sorting it
n_latent <- 2 #dimensions of random site effect alpha (W1 and W2)
np <- ncol(env) + 1

#formatting of starting parameters generated by the function 
seed_mcmc <- c(1234,4321,2345,5432) #setting seeds for reproductibility

###JSDM model presence-absence ----

#model
mod_jSDM <-
  foreach (i = 1:nchains) %dopar% {
    #infering model parameters
    T1 <- Sys.time()
    mod <- jSDM::jSDM_binomial_probit(
      #response variable
      presence_data = veg_sorted_pa, 
      #explanatory variables 
      site_formula = ~.,   
      site_data= env, 
      n_latent=2,
      site_effect="random", 
      #chains
      burnin= 40000, mcmc=40000, thin=40,
      #starting values
      alpha_start=0, beta_start=0,
      lambda_start=0, W_start=0,
      V_alpha=1, 
      #priors
      shape_Valpha=0.1,
      rate_Valpha=0.1,
      mu_beta=0, V_beta=1,
      mu_lambda=0, V_lambda=1,
      #other
      seed = seed_mcmc[i],
      verbose = 0
    )
    T2 <- Sys.time()
    mod$T_jSDM <- difftime(T2,T1)
    return(mod)
  }

stopCluster(clust) #stop cluster
save(mod_jSDM,file="UAV_mod_JSDM_4chains_PA.RData") #save the 4 chains of jSDM model

#estimating the model deviance

summary(mod_jSDM[[1]]$mcmc.Deviance)
plot(mod_jSDM[[1]]$mcmc.Deviance)

#interactions between species

plot_residual_cor(mod_jSDM[[1]])

###beta coefficients from the model and make a mean through iterations (param species) ----

#low density and high density parameters are used to generate confidence interval maps.

sublist <- c(1:4)

spcoefs <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  bcoefs_mean <- lapply(k$mcmc.sp, function(x) colMeans(x))
  bcoefs_mean <- do.call(rbind, bcoefs_mean)
  print(bcoefs_mean)
  colnames(bcoefs_mean) <- c("beta_(Intercept)_mean", "beta_GCC_mean", "beta_BCC_mean", "beta_NDRE_mean", "beta_BAND1_R_mean", "beta_ARI_mean", "lambda_1_mean", "lambda_2_mean")
  
  bcoefs_density_int <- lapply(k$mcmc.sp, function(x) hdi(x))
  bcoefs_lowdensity <- lapply(bcoefs_density_int, function(x) {x[1,]})
  bcoefs_highdensity <- lapply(bcoefs_density_int, function(x) {x[2,]})
  bcoefs_lowdensity <- do.call(rbind, bcoefs_lowdensity)
  bcoefs_highdensity <- do.call(rbind, bcoefs_highdensity)
  colnames(bcoefs_lowdensity) <- c("beta_(Intercept)_low", "beta_GCC_low", "beta_BCC_low", "beta_NDRE_low", "beta_BAND1_R_low", "beta_ARI_low", "lambda_1_low", "lambda_2_low")
  colnames(bcoefs_highdensity) <- c("beta_(Intercept)_high", "beta_GCC_high", "beta_BCC_high", "beta_NDRE_high", "beta_BAND1_R_high", "beta_ARI_high", "lambda_1_high", "lambda_2_high")
  
  bcoefs <- cbind(bcoefs_mean, bcoefs_lowdensity, bcoefs_highdensity)

  return(bcoefs)
})

spcoefs.mean <- apply(simplify2array(spcoefs), 1:2, mean)
spcoefs.mean <- as.data.frame(spcoefs.mean)
spcoefs.mean$CI <- rownames(spcoefs.mean) #this line if we need to sort betacoefs by CI number from network clusters

###sites coeff from the model and make a mean through iterations (param sites) ----

sublist<- c(1:4)

param_site <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  
  acoeff_mean <- apply(k$mcmc.alpha,2,mean)
  acoeff_density_int <- apply(k$mcmc.alpha,2,function(x) hdi(x))
  acoeff_lowdensity <- acoeff_density_int[1,]
  acoeff_highdensity <- acoeff_density_int[2,]
  
  Vacoeff_mean <- apply(k$mcmc.V_alpha,2,mean)
  Vacoeff_density_int <- apply(k$mcmc.V_alpha,2,function(x) hdi(x))
  Vacoeff_lowdensity <- Vacoeff_density_int[1,]
  Vacoeff_highdensity <- Vacoeff_density_int[2,]
  
  W1coeff_mean <- apply(k$mcmc.latent[["lv_1"]],2,mean)
  W1coeff_density_int <- apply(k$mcmc.latent[["lv_1"]],2,function(x) hdi(x))
  W1coeff_lowdensity <- W1coeff_density_int[1,]
  W1coeff_highdensity <- W1coeff_density_int[2,]
  
  W2coeff_mean <- apply(k$mcmc.latent[["lv_2"]],2,mean)
  W2coeff_density_int <- apply(k$mcmc.latent[["lv_2"]],2,function(x) hdi(x))
  W2coeff_lowdensity <- W2coeff_density_int[1,]
  W2coeff_highdensity <- W2coeff_density_int[2,] 
  
  return(list(alpha_mean=acoeff_mean, alpha_low=acoeff_lowdensity, alpha_high=acoeff_highdensity,
              V_alpha_mean=Vacoeff_mean, V_alpha_low=Vacoeff_lowdensity, V_alpha_high=Vacoeff_highdensity,
              W1_mean=W1coeff_mean, W1_low=W1coeff_lowdensity, W1_high=W1coeff_highdensity, 
              W2_mean=W2coeff_mean, W2_low=W2coeff_lowdensity, W2_high=W2coeff_highdensity))
})

sitecoefs <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- param_site[[x]]
  sitecoeff.df <- data.frame(plot=env$site,
                             lat=env$Y_lat_L93,
                             long=env$X_long_L93,
                             alpha_mean=k$alpha_mean,
                             alpha_low=k$alpha_low,
                             alpha_high=k$alpha_high,
                             V_alpha_mean=k$V_alpha_mean,
                             V_alpha_low=k$V_alpha_low,
                             V_alpha_high=k$V_alpha_high,
                             W1_mean=k$W1_mean,
                             W1_low=k$W1_low,
                             W1_high=k$W1_high,
                             W2_mean=k$W2_mean,
                             W2_low=k$W2_low,
                             W2_high=k$W2_high)
  rownames(sitecoeff.df) <- 1:27
  return(sitecoeff.df)
})

sitecoefs.mean <- lapply(X = sublist, FUN=function(x){
  k <- sitecoefs[[x]]
  sitecoeff.df.mean <- data.frame(alpha_mean=k$alpha_mean,
                                  alpha_low=k$alpha_low,
                                  alpha_high=k$alpha_high,
                                  V_alpha_mean=k$V_alpha_mean,
                                  V_alpha_low=k$V_alpha_low,
                                  V_alpha_high=k$V_alpha_high,
                                  W1_mean=k$W1_mean,
                                  W1_low=k$W1_low,
                                  W1_high=k$W1_high,
                                  W2_mean=k$W2_mean,
                                  W2_low=k$W2_low,
                                  W2_high=k$W2_high)
  sitecoeff.df.mean <- as.matrix(sitecoeff.df.mean)
  return(sitecoeff.df.mean)
})

sitecoefs.mean <- apply(simplify2array(sitecoefs.mean), 1:2,  mean)
sitecoefs.mean <- as.data.frame(sitecoefs.mean)
sitecoefs.mean$plot <- env$site
sitecoefs.mean$lat <- env$Y_lat_L93
sitecoefs.mean$long <- env$X_long_L93

save(spcoefs, spcoefs.mean, sitecoefs, sitecoefs.mean,
     file = "UAV_JSDM_param_outputs.RData")

###probit theta latent and theta latent from the model and make a mean through iterations (proability of occurrences for each species) ----

sublist<- c(1:4)

probit_theta_latent <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  prob_theta_lat <- k$probit_theta_latent
  prob_theta_lat <- as.matrix(prob_theta_lat)
  return(prob_theta_lat)
})

probit_theta_latent.mean <- apply(simplify2array(probit_theta_latent), 1:2, mean)
probit_theta_latent.mean <- as.data.frame(probit_theta_latent.mean)

theta_latent <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  theta_lat <- k$theta_latent
  theta_lat <- as.matrix(theta_lat)
  return(theta_lat)
})

theta_latent.mean <- apply(simplify2array(theta_latent), 1:2, mean)
theta_latent.mean <- as.data.frame(theta_latent.mean)

save(probit_theta_latent, probit_theta_latent.mean, theta_latent, theta_latent.mean,
     file = "UAV_JSDM_theta_outputs.RData")

###environmental correlations between VIs for model convergence verification ----

enviro <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  mat <- get_enviro_cor(k)
  fileName <- paste0("Envirocors_", x, ".csv")
  write.table(mat, file = fileName)
  return(mat)
})

enviro.mean <- apply(simplify2array(enviro), 1:2, mean)

output <- lapply(X = sublist, FUN = function(x){
  cor = enviro[[x]]$cor.sig
  return(cor)
})

enviro.mean <- apply(simplify2array(output), 1:2, mean)

###residual correlations for model convergence verification ----

resid <- future_lapply(X = sublist, future.seed = TRUE, FUN = function(x){
  k <- mod_jSDM[[x]]
  mat <- get_residual_cor(k)
  fileName <- paste0("Residcors_", x, ".csv")
  write.table(mat, file = fileName)
  return(mat)
})

resid.mean <- apply(simplify2array(resid), 1:2, mean)

###save data in Rdata format for model validation ----
save(mod_jSDM, spcoefs, enviro, spcoefs.mean, enviro.mean,
     file = "UAV_JSDM_validation_outputs.RData")
